name: Django CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: savannah
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: c3po
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 'latest'  
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env: 
        API_KEY: ${{ secrets.API_KEY }}
        USERNAME: ${{ secrets.MY_USERNAME }}
        SENDER: ${{ secrets.SENDER }}
        
        DATABASE_NAME: savannah
        DATABASE_USER: postgres
        DATABASE_PASSWORD: c3po
        DATABASE_HOST: pgdb 
        DATABASE_PORT: 5432 
        
      run: |
        python manage.py core.test